ALTER TABLE PFIELDS      -- check table name
ADD(GEOM MDSYS.SDO_GEOMETRY);


ALTER TABLE SPAWN       -- check table name
ADD(GEOM MDSYS.SDO_GEOMETRY);


UPDATE PFIELDS SET GEOM =       -- check table name
MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
MDSYS.SDO_ORDINATE_ARRAY(LOWX,LOWY,HIX,HIY)); -- check column names



UPDATE SPAWN SET GEOM =        -- check table name
MDSYS.SDO_GEOMETRY(2001, NULL,
MDSYS.SDO_POINT_TYPE(X,Y,NULL), -- check column names
NULL,NULL);

DELETE FROM USER_SDO_GEOM_METADATA
  WHERE TABLE_NAME = 'PFIELDS' AND COLUMN_NAME = 'GEOM';


DELETE FROM USER_SDO_GEOM_METADATA
  WHERE TABLE_NAME = 'SPAWN' AND COLUMN_NAME = 'GEOM';


INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
'PFIELDS',                         -- check table name
'GEOM',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('X', 0, 50, 0.005),
MDSYS.SDO_DIM_ELEMENT('Y', 0, 50, 0.005)),
NULL);


INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
'SPAWN',                          -- check table name
'GEOM',
MDSYS.SDO_DIM_ARRAY(
MDSYS.SDO_DIM_ELEMENT('X', 0, 50, 0.005),
MDSYS.SDO_DIM_ELEMENT('Y', 0, 50, 0.005)),
NULL);
