CREATE INDEX PFIELDS_IDX
ON PFIELDS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX PATHS_IDEX
ON PATHS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX SPAWN_IDX
ON SPAWN(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX SLOPE_IDX
ON SLOPE(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
