SELECT A.PATH_ID, P.S_X, P.S_Y, E.S_X AS "E_X", E.S_Y AS "E_Y", SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, C.GEOM, 0.005), M.DIMINFO)*D.SCORE_INFL AS "SCORE"
FROM PATHS A, PFIELDS C, USER_SDO_GEOM_METADATA M, GROUND D, PSTART P, PEND E
WHERE M.TABLE_NAME = 'PATHS' AND M.COLUMN_NAME = 'GEOM' AND SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, C.GEOM, 0.005), M.DIMINFO) > 0 AND C.GROUND_ID = D.GROUND_ID AND P.PATH_ID = A.PATH_ID AND E.PATH_ID = A.PATH_ID
ORDER BY A.PATH_ID;
