CREATE TABLE PSTART (POINT_ID NUMBER(2) NOT NULL, PATH_ID NUMBER NOT NULL, S_X NUMBER(2) NOT NULL, S_Y NUMBER(2) NOT NULL, PRIMARY KEY (POINT_ID), FOREIGN KEY (PATH_ID) REFERENCES PATHS(PATH_ID));
CREATE TABLE PEND (POINT_ID NUMBER(2) NOT NULL, PATH_ID NUMBER NOT NULL, S_X NUMBER(2) NOT NULL, S_Y NUMBER(2) NOT NULL, PRIMARY KEY (POINT_ID), FOREIGN KEY (PATH_ID) REFERENCES PATHS(PATH_ID));
