SELECT A.PATH_ID, C.SLOPE_ID, SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, C.GEOM, 0.005), M.DIMINFO) AS "DISTANCE", C.SCORE_INFL
FROM PATHS A, SLOPES C, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'PATHS' AND M.COLUMN_NAME = 'GEOM' AND SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, C.GEOM, 0.005), M.DIMINFO) > 0
ORDER BY A.PATH_ID;
